### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by kevinsimper** [jespera/spdiff.js#1]
You had some examples in your presentation, it could be cool to have some examples in the readme so you could try it in 5 minutes.

**Comment by jespera** [comment]
Yikes! Somehow this issue slipped under my radar. I'll add some examples ASAP!

**Comment by jespera** [comment]
Not very ASAP afterall it seems! Sorry for not actually doing anything about the examples or the entire repo!

**Comment by kevinsimper** [comment]
It still gave me a introduction to what autogenerated code changes was like, more than 1,5 year later we had Kenneth Skovhus to talk about codemod's also 😄

https://copenhagenjs.dk/speaker/?name=kenneth-skovhus
